name: CI/CD

on:
  push:
    branches: [ "github-actions" ]
  pull_request:
    branches: [ "github-actions" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  metadata:
    name: Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract crate information
        id: metadata
        run: |
          cargo metadata --no-deps --format-version 1 | jq -r '"name=" + .packages[0].name' | tee -a $GITHUB_OUTPUT
          cargo metadata --no-deps --format-version 1 | jq -r '"version=v" + .packages[0].version' | tee -a $GITHUB_OUTPUT

      - name: Error if metada.version not equal tag
        if: ${{ github.ref_type == 'tag' }}
        run: |
          if [ "${GITHUB_REF_NAME}" != "${{ steps.metadata.outputs.version  }}" ]; then
            echo "tag: '${{ github.ref }}' is not equal to metadata version: 'refs/tags/${{ steps.metadata.outputs.version }}'"
            exit 1
          fi

    outputs:
      name: ${{ steps.metadata.outputs.name }}
      version: ${{ steps.metadata.outputs.version}}

  lint-and-test:
    name: Run fmt linter and tests
    runs-on: ubuntu-latest
    steps:
#      - uses: ./.github/actions/project-setup
      - name: Install dependencies
        if: runner.os != 'Windows'
        run: |
          sudo apt update
          sudo apt install -y  mold clang pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
        shell: bash
      - name: Add components
        run: |
          rustup component add clippy
          rustup component add rustfmt
      - name: Run fmt
        run: |
          cargo fmt --check
      - name: Run clippy
        env:
          RUSTFLAGS: "-Dwarnings"
        run: |
          cargo clippy --locked --all-targets
      - name: Run tests
        run: |
          cargo test --locked


  build:
    name: Build ${{ matrix.job.name }}
    runs-on: ${{ matrix.job.os }}
#    needs: [metadata, lint-and-test]
    needs: metadata
    strategy:
      fail-fast: false
      matrix:
        job:
          - name: linux-x86_64-gnu
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
#          - name: macOS-x86_64
#            os: macos-latest
#            target: x86_64-apple-darwin
#          - name: windows-x86_64-gnu
#            os: ubuntu-latest
#            target: x86_64-pc-windows-gnu
          - name: windows-x86_64-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
#      - uses: ./.github/actions/project-setup
      - name: Install dependencies
        if: runner.os != 'Windows'
        run: |
          sudo apt update
          sudo apt install -y  mold clang pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
        shell: bash
      - name: Rustup add target
        if: runner.os != 'Windows'
        run: |
          rustup target add ${{ matrix.job.target }}

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2

      - name: Build project
        run: |
          cargo build --locked --release --target ${{ matrix.job.target }}

      - name: Create tarball
        if: github.event_name != 'pull_request'
        id: tarball
        shell: bash
        run: |
          # add .exe for windows
          BIN_SUFFIX=$([[ "${{ matrix.job.target }}" = *"-pc-windows-"* ]] && echo ".exe" || echo "")

          # binary path
          BIN_NAME="${{ needs.metadata.outputs.name }}${BIN_SUFFIX}"
          BIN_PATH="target/${{ matrix.job.target }}/release/${BIN_NAME}"

          # assets path
          ASSET_PATH="assets"

          # package path
          PKG_SUFFIX=$([[ "$CARGO_BUILD_TARGET" != *"-pc-windows-"* ]] && echo ".tar.gz" || echo ".zip")
          PKG_BASENAME=${{ needs.metadata.outputs.name }}-${{ needs.metadata.outputs.version }}-${{ matrix.job.name }}
          PKG_NAME=${PKG_BASENAME}${PKG_SUFFIX}

          # put release files on package directory
          mkdir -p "${PKG_BASENAME}"
          cp "${BIN_PATH}" "${PKG_BASENAME}/."
          cp -rp "${ASSET_PATH}" "${PKG_BASENAME}/."

          # create tarball
          if [ "${PKG_SUFFIX}" = ".zip" ]; then
            if [ "$RUNNER_OS" == "Windows" ]; then
              7z a "${PKG_NAME}" "${PKG_BASENAME}"
            else
              zip -r "${PKG_NAME}" "${PKG_BASENAME}"
            fi
          else
            tar -czf "${PKG_NAME}" "${PKG_BASENAME}"
          fi

          echo "PKG_NAME=${PKG_NAME}" >> $GITHUB_OUTPUT


      - name: "Upload tarball artifact"
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: tarball-${{ steps.tarball.outputs.PKG_NAME }}
          path: ${{ steps.tarball.outputs.PKG_NAME }}

